### ISSUE TITLE
Error "This Clover cannot start outside \EFI\CLOVER\" via USB device

### ISSUE THREAD

**Issue by mackonsti** [jief666/BootloaderChooser#1]
Hello @jief666 I am getting this error when I boot my Hackintosh via a USB device and your latest version of the BootloaderChooser: "This Clover cannot start outside \EFI\CLOVER\"

My folder structure is the following:
/VOLUMES/USB_STICK/ and /EFI/BOOT/BOOTX64.efi <-- your chooser
/VOLUMES/USB_STICK/ and /EFI/CLOVER_r5119/CLOVERX64.efi + drivers + tools + OEM + themes etc.
/VOLUMES/USB_STICK/ and /EFI/CLOVER_r5122/CLOVERX64.efi + drivers + tools + OEM + themes etc.

Under the single /EFI/ folder in root of a previously working USB flash disk (FAT32) with single Clover edition, I place your chooser in BOOT folder and at the same time two different CLOVER_r5xxx folders.

I do get the menu on-screen when selecting to boot via the USB disk, and see 3 entries: the HDD itself, and the two different Clover versions. However, none is working unfortunately, including the HDD itself (which works 100% fine while booting from itself).

I have no idea why this is the case and why BootloaderChooser fails to startup these Clover versions; are they **too new** and perhaps incompatible?

Folder names, Clover name etc. are just as if it were a single Clover EFI boot folder, no changes. Just under different CLOVER_51xx folders tree.

Here is the log that I could capture, straight from the USB disk. Let me know if you need more info, thanks.

[BLC.log](https://github.com/jief666/BootloaderChooser/files/5433808/BLC.log)

**Comment by jief666** [comment]
Interesting. My error was really bad (a copy/paste). So I can't tell yet. But I'd like very much to understand the bug. Please keep that failing configuration for the time to find that bug, if possible.
Try this [BootX64.efi.zip](https://github.com/jief666/BootloaderChooser/files/5435913/BootX64.efi.zip) and send me the log, please.

**Comment by mackonsti** [comment]
Good evening, here are my results/comments and log.

* The build seems a little sluggish and not snappy as before, unless it's a debug build? That's why it's twice the size as before?
* No versioning displayed anywhere in the build (for our mutual reference);
* The detected names in brackets [xxx] only showed [EFI] 3 times despite 1x being on HDD and 2x on USB stick; it wasn't shown as [HDD] per your image on your main page, I mean.
* First 2 options (of 3) show identical as options/paths (one is from HDD's EFI and one is from USB's EFI both in their "CLOVER" folders so can't differentiate)
* First option asked me to reboot and the booloader selector crashed or froze or something else happened, once;
* Second option booted from USB's own EFI/CLOVER
* Third option showed again the error "This Clover cannot start outside \EFI\CLOVER"
* An option to shutdown the computer as the power button didn't turn it off (as it would when normal Clover was running)

Still running on my Lenovo laptop; structure remained as above, root of USB is:
/EFI/BOOT/BOOTX64.efi <-- your chooser
/EFI/CLOVER/CLOVERX64.efi + drivers + tools + OEM + themes etc.
/EFI/CLOVER_r5119/CLOVERX64.efi + drivers + tools + OEM + themes etc.

Renamed CLOVER_r5123 to just CLOVER; should I put some **other name** in LL USB versions of local CLOVER folders?

Logfile attached, really hope it helps: [BLC.log](https://github.com/jief666/BootloaderChooser/files/5441816/BLC.log)

Preferences file in BOOT folder could not be opened by PlistEdit Pro due to a "JSON parsing" error "Illegal start of token [,] at index 0". I think it's because of the ? character in the start: `<?xml version="1.0" encoding="UTF-8"?>`

Konsti

**Comment by jief666** [comment]
> The build seems a little sluggish and not snappy as before, unless it's a debug build? That's why it's twice the size as before?

It is.

> No versioning displayed anywhere in the build (for our mutual reference);

No yet done. It's on my todo list... like a lot of other things.

> The detected names in brackets [xxx] only showed [EFI] 3 times despite 1x being on HDD and 2x on USB stick; it wasn't shown as [HDD] per your image on your main page, I mean.

That's because all your partition are called EFI. You can mount your EFI partition and rename it. Nobody does it, but everyone should.

> First 2 options (of 3) show identical as options/paths (one is from HDD's EFI and one is from USB's EFI both in their "CLOVER" folders so can't differentiate)

That's why everyone should ! :-)

> First option asked me to reboot and the booloader selector crashed or froze or something else happened, once;
> Second option booted from USB's own EFI/CLOVER

It you were asked to reboot, it's because you started Clover, and then quit it to come back to BootloaderChoser. Re-launch  Clover without reboot doesn't work.
I don't about about the freeze. Can't see it in the log. Would be very hard to debug. But if you can reproduce it, we may be able to find the reason.

> Third option showed again the error "This Clover cannot start outside \EFI\CLOVER"

Clover 5119 and 5122 indeed cannot start in a folder that is not called EFI\CLOVER. What BootloaderChooser is right. But in your first log, I also saw some error about not being able to open the efi file. I didn't see it this time.
I didn't tell about Clover folder name that couldn't work with these version because I wanted no change to be able to reproduce the bug. The bug happened before the message "This Clover cannot start outside \EFI\CLOVER\".
From what I see in this second log, everything is working as expected.
I imagine kext and drivers being the same for 5119 and 5122, so you can put both efi files in the same EFI\CLOVER folder.

> An option to shutdown the computer as the power button didn't turn it off (as it would when normal Clover was running)

I don't know why. If you press more than 4 seconds, power buttons always works.

> Preferences file in BOOT folder could not be opened by PlistEdit Pro due to a "JSON parsing" error "Illegal start of token [<] at index 0". I think it's because of the ? character in the start: <?xml version="1.0" encoding="UTF-8"?>

I'll look at that.

**Comment by mackonsti** [comment]
Hello @jief666 thanks for finding time to send some feedback. So you suggest I use different CLOVERxxxx.efi files in a *single* CLOVER folder next to BOOT and under EFI (root)? I didn't understand that in your main page description.

> No yet done. It's on my todo list... like a lot of other things.

I can imagine, sorry to mention the obvious i.e. a version being displayed. BTW I like the BIOS version reference shown!

> That's because all your partition are called EFI. You can mount your EFI partition and rename it. Nobody does it, but everyone should.

I had no idea. I thought it was forbidden! OK thanks for the tip. I may rename my EFI partition as HDD as you suggest.

> Clover 5119 and 5122 indeed cannot start in a folder that is not called EFI\CLOVER. What BootloaderChooser is right.

So you suggest I use different CLOVERxxxx.efi files in a *single* CLOVER folder next to BOOT and under EFI (root)? I didn't understand that in your main page description.

I was hoping to get different, complete CLOVER_xxx folders to play with. What would you suggest? Just change main CLOVERx64.efi while keeping same compiled drivers and ACPI patches and of course, kexts?

> I imagine kext and drivers being the same for 5119 and 5122, so you can put both efi files in the same EFI\CLOVER folder.

Yes, kexts 100% same, only different Clover builds with the same (respective) drivers.

> But in your first log, I also saw some error about not being able to open the efi file. I didn't see it this time. I didn't tell about Clover folder name that couldn't work with these version because I wanted no change to be able to reproduce the bug. The bug happened before the message "This Clover cannot start outside \EFI\CLOVER".
> From what I see in this second log, everything is working as expected.

It seems it worked as I accidentally renamed CLOVER_r5123 to simple CLOVER hence this why it worked and booted, eventually... If you would suggest a way to make your chooser load different, recent versions of Clover (with or without their full tree behind) I would be happy to make some more tests.

I could even make an image/screenshot for you to use on your main README.md as I know you're way too busy with Clover development.

> > An option to shutdown the computer as the power button didn't turn it off (as it would when normal Clover was running)
> I don't know why. If you press more than 4 seconds, power buttons always works.

Of course this is the next obvious action; that's what I did. But when e.g. normal Clover counts-down before booting, pressing simply POWER turns computer off.

Many thanks.

**Comment by jief666** [comment]
- old version can only boot in EFI\Clover. You can create as many FAT32 partition as you want if you'd like completely different CLOVER folder (and name them as you want).

- yes, you can also put different efi file in the same CLOVER folder, naming them as you like.

- we had a misunderstanding because you just said "fails to startup these Clover versions" and because **I didn't read the title** :-) My bad. You were speaking of "This Clover cannot start outside \EFI\CLOVER\", and was thinking of a read error I can see in your log.
I can see in your log that this read error happens when you try to start a Clover located on your NVME ssd. This error didn't happen the second time.
Let me explains why "This Clover cannot start outside \EFI\CLOVER\" is a feature, not a bug. Image you have a CLOVER folder and a CLOVER5119 folder. Without this guard, you could have started the Clover efi file from within CLOVER5119, but all the files (plist, kext, drivers, ACPI, etc.) would have been read from EFI\CLOVER without any visible sign. So don't want that.

- Please open an issue for missing version number, and open another one about the power off. For the power off issue, describe how to reproduce.

**Comment by mackonsti** [comment]
Good morning and thanks again. So please, a final piece of help/guide perhaps worthy of making it to the front page: How to set up test EFIs including the one on the boot SSD/NVMe?

Scenario: SSD/NVMe with normal GUID partition EFI and single normal Clover running inside just fine. And I want to test a new version (like the one you compiled for me, pre-OC 5123) on a USB thumbdrive. But on that drive I had also another working previous Clover (say 5119 with full structure) and a test OpenCore folder (renamed). What is the correct folder structure to boot from both NVMe normally and the 2 Clover(s) and 1 or 2 OpenCore(s)?

Perhaps consider putting this text if you have time, to your main README.md page. Many thanks again.

**Comment by jief666** [comment]
If you want a complete separate CLOVER folder to be able to change the configuration :
Because Clover 5123 cannot work outside EFI\CLOVER folder, you'll have to create a new FAT32 partition to put your new clover on it. No need to put a EFI\BOOT folder on this new partition.
BootloaderChooser should see it and propose to boot on it.

Documentation is a problem, especially because we have no help on that and the development take so much time already...

**Comment by mackonsti** [comment]
Thanks @jief666 for the sake of information and for other people possibly reading, any idea if a USB flash stick would work with multiple FAT32 partitions to be able to boot different Clover flavours? OK by multiple I mean 2 or 3 maximum.
I would assume your bootloader chooser should reside on the very first FAT32 partition...
Thanks again.

**Comment by jief666** [comment]
It should work. 10 partitions if you'd like. You need only one BootloadeChooser. Not necessarily on a USB stick. Anywhere that you computer can boot on it.
BootloaderChooser search for efi file on all volumes it found.

**Comment by nikhilraj9999** [comment]
Please help me out with this i don't get it . I copied bootx64.efi to efi/boot folder for clover also tried with oc 0.6.1 but when i boot with legacy usb i get error boot0 error
When i boot with uefi usb i get black screen nothing else also num key hang on keyboard can't even ctlr alt del to restart . Nit see the menu 1ce even

**Comment by jief666** [comment]
Sorry.
But this seems not a BootLoaderChooser issue.
Do not hijack a closed issue, please.
Maybe try in Clover general forum.
Thanks.
